name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 20.x }
      - name: Build
        run: |
          corepack enable
          corepack prepare yarn@4.4.1
          yarn install --frozen-lockfile
          yarn build
